/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.23).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package es.jpargoteo.fibonacci.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

public interface NumbersApi {

    @Operation(summary = "Find your golden number", description = "Finds the number in the Fibonacci's sequence for one given number.", tags={ "numbers" })
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Your golden number was find successfully!!", content = @Content(schema = @Schema(implementation = Long.class))),

            @ApiResponse(responseCode = "405", description = "The introduced number is not valid.", content = @Content(schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/numbers/{number}",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<Long> getNumber(@Parameter(in = ParameterIn.PATH, description = "Number for which to find its value in the sequence.", required = true, schema = @Schema()) @PathVariable("number") Long number);

}

