/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.23).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package es.jpargoteo.fibonacci.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;

public interface SequencesApi {

    @Operation(summary = "Find your magic sequence", description = "Finds the Fibonacci's sequence for one given number.", tags = {"sequences"})
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Your magic sequence was find successfully!!", content = @Content(array = @ArraySchema(schema = @Schema(implementation = Long.class)))),

            @ApiResponse(responseCode = "405", description = "The introduced number is not valid.", content = @Content(schema = @Schema(implementation = Error.class)))})
    @RequestMapping(value = "/sequences/{number}",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<Long>> getSequence(@Parameter(in = ParameterIn.PATH, description = "Number for which to find the sequence.", required = true, schema = @Schema()) @PathVariable("number") Long number);

}

